create database `projeto-vendas`;

use `projeto-vendas`;

CREATE TABLE USUARIO (
    COD_USUARIO    INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_COMPLETO  VARCHAR(120) NOT NULL,
    USUARIO        VARCHAR(50) NOT NULL,
    SENHA          VARCHAR(50) NOT NULL,
    DT_HR_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE CLIENTE(
    COD_CLIENTE    INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_COMPLETO  VARCHAR(120) NOT NULL,
    CPF_CNPJ       VARCHAR(14),
    DT_HR_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE PRODUTO(
    COD_PRODUTO    INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO      VARCHAR(100) NOT NULL,
    EAN            VARCHAR(14),
    ATIVO          CHAR(1) NOT NULL DEFAULT 'I' CHECK (ATIVO = 'A' OR ATIVO = 'I' OR ATIVO = 'E'),
    PRECO1         NUMERIC(15,2) NOT NULL DEFAULT 0,
    PRECO2         NUMERIC(15,2) NOT NULL DEFAULT 0,
    PRECO3         NUMERIC(15,2) NOT NULL DEFAULT 0,
    DT_HR_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE VENDA (
    COD_VENDA      INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_USUARIO    INTEGER NOT NULL,
    COD_CLIENTE    INTEGER NOT NULL,
    VALOR_TOTAL    NUMERIC(15,2) NOT NULL DEFAULT 0,
    DT_HR_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT     FK_USUARIO FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO(COD_USUARIO),
    CONSTRAINT     FK_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
);    

CREATE TABLE VENDA_ITEM(
  COD_VENDA_ITEM INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  COD_VENDA      INTEGER NOT NULL,
  COD_PRODUTO    INTEGER NOT NULL,  
  QUANTIDADE     NUMERIC(15,3) NOT NULL,
  VALOR_UNITARIO NUMERIC(15,3) NOT NULL,
  VALOR_TOTAL    NUMERIC(15,3) NOT NULL,  
  DT_HR_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  
  CONSTRAINT     FK_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),  
  CONSTRAINT     FK_VENDA FOREIGN KEY (COD_VENDA) REFERENCES VENDA(COD_VENDA)  
);




